# Generated by Django 2.2.14 on 2020-10-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testdata', models.TextField()),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
